-- MySQL Script generated by MySQL Workbench
-- Fri Aug 16 17:44:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hospital_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hospital_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hospital_db` DEFAULT CHARACTER SET utf8 ;
USE `Hospital_db` ;

-- -----------------------------------------------------
-- Table `Hospital_db`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Pacientes` (
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `telefone` INT(11) NULL,
  `Genero` BINARY(2) NOT NULL,
  `cartao_sus` INT(15) NOT NULL,
  PRIMARY KEY (`CPF`));


-- -----------------------------------------------------
-- Table `Hospital_db`.`recepcao_externa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`recepcao_externa` (
  `guiche_recepcao` INT NOT NULL,
  PRIMARY KEY (`guiche_recepcao`));


-- -----------------------------------------------------
-- Table `Hospital_db`.`Recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Recepcionista` (
  `CPF_rece` INT(11) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  `recepcao_externa_guiche_recepcao` INT NOT NULL,
  PRIMARY KEY (`CPF_rece`),
  INDEX `fk_Recepcionista_recepcao_externa1_idx` (`recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  CONSTRAINT `fk_Recepcionista_recepcao_externa1`
    FOREIGN KEY (`recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`recepcao_externa` (`guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Hospital_db`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Registro` (
  `Pacientes_CPF` INT(11) NOT NULL,
  `recepcao_externa_guiche_recepcao` INT NOT NULL,
  PRIMARY KEY (`Pacientes_CPF`, `recepcao_externa_guiche_recepcao`),
  INDEX `fk_Pacientes_has_recepcao_externa_recepcao_externa1_idx` (`recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  INDEX `fk_Pacientes_has_recepcao_externa_Pacientes_idx` (`Pacientes_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Pacientes_has_recepcao_externa_Pacientes`
    FOREIGN KEY (`Pacientes_CPF`)
    REFERENCES `Hospital_db`.`Pacientes` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacientes_has_recepcao_externa_recepcao_externa1`
    FOREIGN KEY (`recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`recepcao_externa` (`guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Hospital_db`.`Classificacao_vermelho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Classificacao_vermelho` (
  `Emergencia_id` INT NOT NULL,
  PRIMARY KEY (`Emergencia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Classificacao_amarelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Classificacao_amarelo` (
  `Urgente_id` INT NOT NULL,
  PRIMARY KEY (`Urgente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Classificacao_verde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Classificacao_verde` (
  `Nao_urgente_id` INT NOT NULL,
  PRIMARY KEY (`Nao_urgente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Classificacao_azul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Classificacao_azul` (
  `Nao_urgente_id` INT NOT NULL,
  PRIMARY KEY (`Nao_urgente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Enfermeiro_Triagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Enfermeiro_Triagem` (
  `Coren_tri` INT NOT NULL,
  `Nome_tri` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Sus_tri` INT(15) NULL,
  `Telefone_tri` INT(11) NULL,
  `Triagem_idTriagem` INT NOT NULL,
  `Triagem_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Triagem_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Triagem_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Triagem_idTriagem1` INT NOT NULL,
  `Triagem_Registro_Pacientes_CPF1` INT(11) NOT NULL,
  `Triagem_Registro_recepcao_externa_guiche_recepcao1` INT NOT NULL,
  `Triagem_Classificacao_de_risco_idClassificacao_de_risco1` INT NOT NULL,
  PRIMARY KEY (`Coren_tri`, `Triagem_idTriagem`, `Triagem_Registro_Pacientes_CPF`, `Triagem_Registro_recepcao_externa_guiche_recepcao`, `Triagem_Classificacao_de_risco_idClassificacao_de_risco`),
  INDEX `fk_Enfermeiro_Triagem_Triagem1_idx` (`Triagem_idTriagem1` ASC, `Triagem_Registro_Pacientes_CPF1` ASC, `Triagem_Registro_recepcao_externa_guiche_recepcao1` ASC, `Triagem_Classificacao_de_risco_idClassificacao_de_risco1` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_Triagem_Triagem1`
    FOREIGN KEY (`Triagem_idTriagem1` , `Triagem_Registro_Pacientes_CPF1` , `Triagem_Registro_recepcao_externa_guiche_recepcao1` , `Triagem_Classificacao_de_risco_idClassificacao_de_risco1`)
    REFERENCES `Hospital_db`.`Triagem` (`idTriagem` , `Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao` , `Classificacao_de_risco_idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Classificacao_de_risco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Classificacao_de_risco` (
  `idClassificacao_de_risco` INT NOT NULL,
  `Classificacao_vermelho_Emergencia_id` INT NOT NULL,
  `Classificacao_amarelo_Urgente_id` INT NOT NULL,
  `Classificacao_verde_Nao_urgente_id` INT NOT NULL,
  `Classificacao_azul_Nao_urgente_id` INT NOT NULL,
  `Enfermeiro_Triagem_Coren` INT NOT NULL,
  `Enfermeiro_Triagem_Triagem_idTriagem` INT NOT NULL,
  `Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  PRIMARY KEY (`idClassificacao_de_risco`, `Enfermeiro_Triagem_Coren`, `Enfermeiro_Triagem_Triagem_idTriagem`, `Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF`, `Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao`, `Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`),
  INDEX `fk_Classificacao_de_risco_Classificacao_vermelho1_idx` (`Classificacao_vermelho_Emergencia_id` ASC) VISIBLE,
  INDEX `fk_Classificacao_de_risco_Classificacao_amarelo1_idx` (`Classificacao_amarelo_Urgente_id` ASC) VISIBLE,
  INDEX `fk_Classificacao_de_risco_Classificacao_verde1_idx` (`Classificacao_verde_Nao_urgente_id` ASC) VISIBLE,
  INDEX `fk_Classificacao_de_risco_Classificacao_azul1_idx` (`Classificacao_azul_Nao_urgente_id` ASC) VISIBLE,
  INDEX `fk_Classificacao_de_risco_Enfermeiro_Triagem1_idx` (`Enfermeiro_Triagem_Coren` ASC, `Enfermeiro_Triagem_Triagem_idTriagem` ASC, `Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` ASC, `Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` ASC, `Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` ASC) VISIBLE,
  CONSTRAINT `fk_Classificacao_de_risco_Classificacao_vermelho1`
    FOREIGN KEY (`Classificacao_vermelho_Emergencia_id`)
    REFERENCES `Hospital_db`.`Classificacao_vermelho` (`Emergencia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classificacao_de_risco_Classificacao_amarelo1`
    FOREIGN KEY (`Classificacao_amarelo_Urgente_id`)
    REFERENCES `Hospital_db`.`Classificacao_amarelo` (`Urgente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classificacao_de_risco_Classificacao_verde1`
    FOREIGN KEY (`Classificacao_verde_Nao_urgente_id`)
    REFERENCES `Hospital_db`.`Classificacao_verde` (`Nao_urgente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classificacao_de_risco_Classificacao_azul1`
    FOREIGN KEY (`Classificacao_azul_Nao_urgente_id`)
    REFERENCES `Hospital_db`.`Classificacao_azul` (`Nao_urgente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classificacao_de_risco_Enfermeiro_Triagem1`
    FOREIGN KEY (`Enfermeiro_Triagem_Coren` , `Enfermeiro_Triagem_Triagem_idTriagem` , `Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    REFERENCES `Hospital_db`.`Enfermeiro_Triagem` (`Coren_tri` , `Triagem_idTriagem` , `Triagem_Registro_Pacientes_CPF` , `Triagem_Registro_recepcao_externa_guiche_recepcao` , `Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Triagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Triagem` (
  `idTriagem` INT NOT NULL,
  `Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  PRIMARY KEY (`idTriagem`, `Registro_Pacientes_CPF`, `Registro_recepcao_externa_guiche_recepcao`, `Classificacao_de_risco_idClassificacao_de_risco`),
  INDEX `fk_Triagem_Registro1_idx` (`Registro_Pacientes_CPF` ASC, `Registro_recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  INDEX `fk_Triagem_Classificacao_de_risco1_idx` (`Classificacao_de_risco_idClassificacao_de_risco` ASC) VISIBLE,
  CONSTRAINT `fk_Triagem_Registro1`
    FOREIGN KEY (`Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`Registro` (`Pacientes_CPF` , `recepcao_externa_guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Triagem_Classificacao_de_risco1`
    FOREIGN KEY (`Classificacao_de_risco_idClassificacao_de_risco`)
    REFERENCES `Hospital_db`.`Classificacao_de_risco` (`idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Diretor_tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Diretor_tecnico` (
  `CRM_dire` INT NOT NULL,
  `nome_dire_tec` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `SuS_dire_tec` INT(15) NULL,
  `Telefone_dire_tec` INT(11) NULL,
  PRIMARY KEY (`CRM_dire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Clinico_Geral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Clinico_Geral` (
  `CRM_geral` INT NOT NULL,
  `Nome_geral` VARCHAR(45) NULL,
  `SUS` VARCHAR(45) NULL,
  `Data_Nascimento` DATE NULL,
  `Telefone_geral` INT(11) NULL,
  `Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Classificacao_de_risco_Enfermeiro_Triagem_Coren` INT NOT NULL,
  `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` INT NOT NULL,
  `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_geral`, `Classificacao_de_risco_idClassificacao_de_risco`, `Classificacao_de_risco_Enfermeiro_Triagem_Coren`, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem`, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF`, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao`, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Clinico_Geral_Classificacao_de_risco1_idx` (`Classificacao_de_risco_idClassificacao_de_risco` ASC, `Classificacao_de_risco_Enfermeiro_Triagem_Coren` ASC, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` ASC, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` ASC, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` ASC, `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` ASC) VISIBLE,
  INDEX `fk_Clinico_Geral_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Clinico_Geral_Classificacao_de_risco1`
    FOREIGN KEY (`Classificacao_de_risco_idClassificacao_de_risco` , `Classificacao_de_risco_Enfermeiro_Triagem_Coren` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    REFERENCES `Hospital_db`.`Classificacao_de_risco` (`idClassificacao_de_risco` , `Enfermeiro_Triagem_Coren` , `Enfermeiro_Triagem_Triagem_idTriagem` , `Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clinico_Geral_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Tecnico_RaioX`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Tecnico_RaioX` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Idade` DATE NULL,
  `Turno` BINARY(2) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Farmacia` (
  `idRemedio` INT NOT NULL,
  `Nome_remedio` VARCHAR(45) NULL,
  `Quantia_remedio` INT(30) NULL,
  PRIMARY KEY (`idRemedio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Bloco_cirurgico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Bloco_cirurgico` (
  `Mapa_cirurgia` LONGTEXT NOT NULL,
  `idBloco_cirurgicocol` INT NOT NULL,
  `Sala_cirurgia` BINARY(3) NULL,
  PRIMARY KEY (`idBloco_cirurgicocol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Sala_ambulatorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Sala_ambulatorial` (
  `Assento_ambulatorial` INT NOT NULL,
  `Tipo de Procedimento` VARCHAR(45) NULL,
  PRIMARY KEY (`Assento_ambulatorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Pronto_socorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Pronto_socorro` (
  `idPronto_socorro` INT NOT NULL,
  `Sala_ambulatorial_Assento_ambulatorial` INT NOT NULL,
  PRIMARY KEY (`idPronto_socorro`),
  INDEX `fk_Pronto_socorro_Sala_ambulatorial1_idx` (`Sala_ambulatorial_Assento_ambulatorial` ASC) VISIBLE,
  CONSTRAINT `fk_Pronto_socorro_Sala_ambulatorial1`
    FOREIGN KEY (`Sala_ambulatorial_Assento_ambulatorial`)
    REFERENCES `Hospital_db`.`Sala_ambulatorial` (`Assento_ambulatorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Prontuario_clinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Prontuario_clinico` (
  `idProntuario_clinico` INT NOT NULL,
  `Clinico_Geral_CRM` INT NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` INT NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` INT NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Tecnico_RaioX_CPF` INT NOT NULL,
  `Pronto_socorro_idPronto_socorro` INT NOT NULL,
  `Farmacia_idRemedio` INT NOT NULL,
  `Bloco_cirurgico_idBloco_cirurgicocol` INT NOT NULL,
  `Pronto_socorro_idPronto_socorro1` INT NOT NULL,
  PRIMARY KEY (`idProntuario_clinico`, `Clinico_Geral_CRM`, `Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco`, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren`, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem`, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF`, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao`, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`, `Tecnico_RaioX_CPF`, `Pronto_socorro_idPronto_socorro`, `Farmacia_idRemedio`, `Bloco_cirurgico_idBloco_cirurgicocol`, `Pronto_socorro_idPronto_socorro1`),
  INDEX `fk_Prontuario_clinico_Clinico_Geral1_idx` (`Clinico_Geral_CRM` ASC, `Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` ASC, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` ASC, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` ASC, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` ASC, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` ASC, `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` ASC) VISIBLE,
  INDEX `fk_Prontuario_clinico_Tecnico_RaioX1_idx` (`Tecnico_RaioX_CPF` ASC) VISIBLE,
  INDEX `fk_Prontuario_clinico_Farmacia1_idx` (`Farmacia_idRemedio` ASC) VISIBLE,
  INDEX `fk_Prontuario_clinico_Bloco_cirurgico1_idx` (`Bloco_cirurgico_idBloco_cirurgicocol` ASC) VISIBLE,
  INDEX `fk_Prontuario_clinico_Pronto_socorro1_idx` (`Pronto_socorro_idPronto_socorro1` ASC) VISIBLE,
  CONSTRAINT `fk_Prontuario_clinico_Clinico_Geral1`
    FOREIGN KEY (`Clinico_Geral_CRM` , `Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    REFERENCES `Hospital_db`.`Clinico_Geral` (`CRM_geral` , `Classificacao_de_risco_idClassificacao_de_risco` , `Classificacao_de_risco_Enfermeiro_Triagem_Coren` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_clinico_Tecnico_RaioX1`
    FOREIGN KEY (`Tecnico_RaioX_CPF`)
    REFERENCES `Hospital_db`.`Tecnico_RaioX` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_clinico_Farmacia1`
    FOREIGN KEY (`Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Farmacia` (`idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_clinico_Bloco_cirurgico1`
    FOREIGN KEY (`Bloco_cirurgico_idBloco_cirurgicocol`)
    REFERENCES `Hospital_db`.`Bloco_cirurgico` (`idBloco_cirurgicocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_clinico_Pronto_socorro1`
    FOREIGN KEY (`Pronto_socorro_idPronto_socorro1`)
    REFERENCES `Hospital_db`.`Pronto_socorro` (`idPronto_socorro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Nutricionista` (
  `CRN` INT NOT NULL,
  `Nome_nutri` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_nutri` INT(11) NULL,
  `Cartao_sus_nutri` INT(15) NULL,
  PRIMARY KEY (`CRN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Fisioterapia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Fisioterapia` (
  `coffito_fisio` INT NOT NULL,
  `Nome_fisio` VARCHAR(45) NULL,
  `Data-Nascimento` DATE NULL,
  `telefone_fisio` INT(11) NULL,
  `Cartao_sus_fisio` INT(15) NULL,
  PRIMARY KEY (`coffito_fisio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Clinica` (
  `idClinica` INT NOT NULL,
  PRIMARY KEY (`idClinica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Recepcao_interna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Recepcao_interna` (
  `idRecepcao_interna` INT NOT NULL,
  `Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`idRecepcao_interna`, `Clinica_idClinica`),
  INDEX `fk_Recepcao_interna_Clinica1_idx` (`Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Recepcao_interna_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Prontuario_internado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Prontuario_internado` (
  `idProntuario_internado` INT NOT NULL,
  `Prontuario_clinico_idProntuario_clinico` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_CRM` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` INT NOT NULL,
  `Nutricionista_CRN` INT NOT NULL,
  `Fisioterapia_coffito_fisio` INT NOT NULL,
  `Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  PRIMARY KEY (`idProntuario_internado`, `Prontuario_clinico_idProntuario_clinico`, `Prontuario_clinico_Clinico_Geral_CRM`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao`, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`, `Nutricionista_CRN`, `Fisioterapia_coffito_fisio`, `Recepcao_interna_idRecepcao_interna`),
  INDEX `fk_Prontuario_internado_Prontuario_clinico1_idx` (`Prontuario_clinico_idProntuario_clinico` ASC, `Prontuario_clinico_Clinico_Geral_CRM` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` ASC, `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco` ASC) VISIBLE,
  INDEX `fk_Prontuario_internado_Nutricionista1_idx` (`Nutricionista_CRN` ASC) VISIBLE,
  INDEX `fk_Prontuario_internado_Fisioterapia1_idx` (`Fisioterapia_coffito_fisio` ASC) VISIBLE,
  INDEX `fk_Prontuario_internado_Recepcao_interna1_idx` (`Recepcao_interna_idRecepcao_interna` ASC) VISIBLE,
  CONSTRAINT `fk_Prontuario_internado_Prontuario_clinico1`
    FOREIGN KEY (`Prontuario_clinico_idProntuario_clinico` , `Prontuario_clinico_Clinico_Geral_CRM` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Prontuario_clinico_Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    REFERENCES `Hospital_db`.`Prontuario_clinico` (`idProntuario_clinico` , `Clinico_Geral_CRM` , `Clinico_Geral_Classificacao_de_risco_idClassificacao_de_risco` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Coren` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_idTriagem` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_Pacientes_CPF` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Registro_recepcao_externa_guiche_recepcao` , `Clinico_Geral_Classificacao_de_risco_Enfermeiro_Triagem_Triagem_Classificacao_de_risco_idClassificacao_de_risco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_internado_Nutricionista1`
    FOREIGN KEY (`Nutricionista_CRN`)
    REFERENCES `Hospital_db`.`Nutricionista` (`CRN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_internado_Fisioterapia1`
    FOREIGN KEY (`Fisioterapia_coffito_fisio`)
    REFERENCES `Hospital_db`.`Fisioterapia` (`coffito_fisio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prontuario_internado_Recepcao_interna1`
    FOREIGN KEY (`Recepcao_interna_idRecepcao_interna`)
    REFERENCES `Hospital_db`.`Recepcao_interna` (`idRecepcao_interna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Exames` (
  `idExames` INT NOT NULL,
  `Sala` INT(1) NULL,
  `Horas_exame` DATE NULL,
  `Tecnico_RaioX_CPF` INT NOT NULL,
  PRIMARY KEY (`idExames`),
  INDEX `fk_Exames_Tecnico_RaioX1_idx` (`Tecnico_RaioX_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Exames_Tecnico_RaioX1`
    FOREIGN KEY (`Tecnico_RaioX_CPF`)
    REFERENCES `Hospital_db`.`Tecnico_RaioX` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Enfermeiro_pronto_socorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Enfermeiro_pronto_socorro` (
  `Coren_pron` INT NOT NULL,
  `Nome_pron` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_pron` INT(11) NULL,
  `Turno_pron` BINARY(2) NULL,
  `Pronto_socorro_idPronto_socorro` INT NOT NULL,
  `Farmacia_idRemedio` INT NOT NULL,
  `Pronto_socorro_idPronto_socorro1` INT NOT NULL,
  PRIMARY KEY (`Coren_pron`, `Pronto_socorro_idPronto_socorro`, `Farmacia_idRemedio`),
  INDEX `fk_Enfermeiro_pronto_socorro_Farmacia1_idx` (`Farmacia_idRemedio` ASC) VISIBLE,
  INDEX `fk_Enfermeiro_pronto_socorro_Pronto_socorro1_idx` (`Pronto_socorro_idPronto_socorro1` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_pronto_socorro_Farmacia1`
    FOREIGN KEY (`Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Farmacia` (`idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermeiro_pronto_socorro_Pronto_socorro1`
    FOREIGN KEY (`Pronto_socorro_idPronto_socorro1`)
    REFERENCES `Hospital_db`.`Pronto_socorro` (`idPronto_socorro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Farmaceutico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Farmaceutico` (
  `idFarmaceutico` INT NOT NULL,
  `Nome_farma` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Cartao_sus_farma` INT(15) NULL,
  `Turno_farma` BINARY(2) NULL,
  `Farmacia_idRemedio` INT NOT NULL,
  PRIMARY KEY (`idFarmaceutico`),
  INDEX `fk_Farmaceutico_Farmacia1_idx` (`Farmacia_idRemedio` ASC) VISIBLE,
  CONSTRAINT `fk_Farmaceutico_Farmacia1`
    FOREIGN KEY (`Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Farmacia` (`idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Enfermeiro_bloco_cirurgico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Enfermeiro_bloco_cirurgico` (
  `Coren_blo` INT NOT NULL,
  `Nome_blo` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Cartao_sus` INT(15) NULL,
  `Turno_blo` BINARY(2) NULL,
  `Bloco_cirurgico_idBloco_cirurgicocol` INT NOT NULL,
  PRIMARY KEY (`Coren_blo`),
  INDEX `fk_Enfermeiro_bloco_cirurgico_Bloco_cirurgico1_idx` (`Bloco_cirurgico_idBloco_cirurgicocol` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_bloco_cirurgico_Bloco_cirurgico1`
    FOREIGN KEY (`Bloco_cirurgico_idBloco_cirurgicocol`)
    REFERENCES `Hospital_db`.`Bloco_cirurgico` (`idBloco_cirurgicocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Cirurgiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Cirurgiao` (
  `CRM_ciru` INT NOT NULL,
  `Nome_ciru` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Cartao_sus_ciru` INT(15) NULL,
  `Telefone_ciru` INT(11) NULL,
  `Bloco_cirurgico_idBloco_cirurgicocol` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_ciru`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Cirurgiao_Bloco_cirurgico1_idx` (`Bloco_cirurgico_idBloco_cirurgicocol` ASC) VISIBLE,
  INDEX `fk_Cirurgiao_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Cirurgiao_Bloco_cirurgico1`
    FOREIGN KEY (`Bloco_cirurgico_idBloco_cirurgicocol`)
    REFERENCES `Hospital_db`.`Bloco_cirurgico` (`idBloco_cirurgicocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cirurgiao_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Anestesista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Anestesista` (
  `CRM_anes` INT NOT NULL,
  `Nome_anes` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_anes` INT(11) NULL,
  `Cartao_sus_anes` INT(15) NULL,
  `Bloco_cirurgico_idBloco_cirurgicocol` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_anes`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Anestesista_Bloco_cirurgico1_idx` (`Bloco_cirurgico_idBloco_cirurgicocol` ASC) VISIBLE,
  INDEX `fk_Anestesista_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Anestesista_Bloco_cirurgico1`
    FOREIGN KEY (`Bloco_cirurgico_idBloco_cirurgicocol`)
    REFERENCES `Hospital_db`.`Bloco_cirurgico` (`idBloco_cirurgicocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Anestesista_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Enfermeiro_clinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Enfermeiro_clinico` (
  `Coren_cli` INT NOT NULL,
  `Nome_cli` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone` INT(11) NULL,
  `Cartao_sus_cli` INT(15) NULL,
  `Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`Coren_cli`),
  INDEX `fk_Enfermeiro_clinico_Clinica1_idx` (`Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Enfermeiro_clinico_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Sala_pediatria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Sala_pediatria` (
  `idSala_pediatria` INT GENERATED ALWAYS AS () VIRTUAL,
  `Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`idSala_pediatria`, `Recepcao_interna_idRecepcao_interna`, `Recepcao_interna_Clinica_idClinica`),
  INDEX `fk_Sala_pediatria_Recepcao_interna1_idx` (`Recepcao_interna_idRecepcao_interna` ASC, `Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_pediatria_Recepcao_interna1`
    FOREIGN KEY (`Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Recepcao_interna` (`idRecepcao_interna` , `Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Sala_vermelha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Sala_vermelha` (
  `idSala_vermelha` INT NOT NULL,
  `Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`idSala_vermelha`, `Recepcao_interna_idRecepcao_interna`, `Recepcao_interna_Clinica_idClinica`),
  INDEX `fk_Sala_vermelha_Recepcao_interna1_idx` (`Recepcao_interna_idRecepcao_interna` ASC, `Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_vermelha_Recepcao_interna1`
    FOREIGN KEY (`Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Recepcao_interna` (`idRecepcao_interna` , `Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Apartamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Apartamentos` (
  `Salas_Apartamentos` INT NOT NULL,
  `Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`Salas_Apartamentos`, `Recepcao_interna_idRecepcao_interna`, `Recepcao_interna_Clinica_idClinica`),
  INDEX `fk_Apartamentos_Recepcao_interna1_idx` (`Recepcao_interna_idRecepcao_interna` ASC, `Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Apartamentos_Recepcao_interna1`
    FOREIGN KEY (`Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Recepcao_interna` (`idRecepcao_interna` , `Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Apoio` (
  `idApoio` INT NOT NULL,
  `Sala_pediatria_idSala_pediatria` INT NOT NULL,
  `Sala_pediatria_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Sala_pediatria_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  `Sala_vermelha_idSala_vermelha` INT NOT NULL,
  `Sala_vermelha_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Sala_vermelha_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  `Apartamentos_Salas_Apartamentos` INT NOT NULL,
  `Apartamentos_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Apartamentos_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  PRIMARY KEY (`idApoio`, `Sala_pediatria_idSala_pediatria`, `Sala_pediatria_Recepcao_interna_idRecepcao_interna`, `Sala_pediatria_Recepcao_interna_Clinica_idClinica`, `Sala_vermelha_idSala_vermelha`, `Sala_vermelha_Recepcao_interna_idRecepcao_interna`, `Sala_vermelha_Recepcao_interna_Clinica_idClinica`, `Apartamentos_Salas_Apartamentos`, `Apartamentos_Recepcao_interna_idRecepcao_interna`, `Apartamentos_Recepcao_interna_Clinica_idClinica`),
  INDEX `fk_Apoio_Sala_pediatria1_idx` (`Sala_pediatria_idSala_pediatria` ASC, `Sala_pediatria_Recepcao_interna_idRecepcao_interna` ASC, `Sala_pediatria_Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  INDEX `fk_Apoio_Sala_vermelha1_idx` (`Sala_vermelha_idSala_vermelha` ASC, `Sala_vermelha_Recepcao_interna_idRecepcao_interna` ASC, `Sala_vermelha_Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  INDEX `fk_Apoio_Apartamentos1_idx` (`Apartamentos_Salas_Apartamentos` ASC, `Apartamentos_Recepcao_interna_idRecepcao_interna` ASC, `Apartamentos_Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Apoio_Sala_pediatria1`
    FOREIGN KEY (`Sala_pediatria_idSala_pediatria` , `Sala_pediatria_Recepcao_interna_idRecepcao_interna` , `Sala_pediatria_Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Sala_pediatria` (`idSala_pediatria` , `Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoio_Sala_vermelha1`
    FOREIGN KEY (`Sala_vermelha_idSala_vermelha` , `Sala_vermelha_Recepcao_interna_idRecepcao_interna` , `Sala_vermelha_Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Sala_vermelha` (`idSala_vermelha` , `Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apoio_Apartamentos1`
    FOREIGN KEY (`Apartamentos_Salas_Apartamentos` , `Apartamentos_Recepcao_interna_idRecepcao_interna` , `Apartamentos_Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Apartamentos` (`Salas_Apartamentos` , `Recepcao_interna_idRecepcao_interna` , `Recepcao_interna_Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Cozinha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Cozinha` (
  `idCozinha` INT NOT NULL,
  `Nutricionista_CRN` INT NOT NULL,
  `Apoio_idApoio` INT NOT NULL,
  PRIMARY KEY (`idCozinha`, `Apoio_idApoio`),
  INDEX `fk_Cozinha_Nutricionista1_idx` (`Nutricionista_CRN` ASC) VISIBLE,
  INDEX `fk_Cozinha_Apoio1_idx` (`Apoio_idApoio` ASC) VISIBLE,
  CONSTRAINT `fk_Cozinha_Nutricionista1`
    FOREIGN KEY (`Nutricionista_CRN`)
    REFERENCES `Hospital_db`.`Nutricionista` (`CRN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cozinha_Apoio1`
    FOREIGN KEY (`Apoio_idApoio`)
    REFERENCES `Hospital_db`.`Apoio` (`idApoio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Cozinheiras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Cozinheiras` (
  `CPF_coz` INT NOT NULL,
  `Nome_coz` VARCHAR(45) NULL,
  `Data_nascimento` VARCHAR(45) NULL,
  `Turno` BINARY(2) NULL,
  `Telefone_coz` INT(11) NULL,
  `Cozinha_idCozinha` INT NOT NULL,
  PRIMARY KEY (`CPF_coz`),
  INDEX `fk_Cozinheiras_Cozinha1_idx` (`Cozinha_idCozinha` ASC) VISIBLE,
  CONSTRAINT `fk_Cozinheiras_Cozinha1`
    FOREIGN KEY (`Cozinha_idCozinha`)
    REFERENCES `Hospital_db`.`Cozinha` (`idCozinha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Manutencao` (
  `CPF_manu` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_manu` INT(11) NULL,
  `Apoio_idApoio` INT NOT NULL,
  PRIMARY KEY (`CPF_manu`, `Apoio_idApoio`),
  INDEX `fk_Manutencao_Apoio1_idx` (`Apoio_idApoio` ASC) VISIBLE,
  CONSTRAINT `fk_Manutencao_Apoio1`
    FOREIGN KEY (`Apoio_idApoio`)
    REFERENCES `Hospital_db`.`Apoio` (`idApoio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Zeladoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Zeladoria` (
  `CPF_zela` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_zela` INT(11) NULL,
  `Apoio_idApoio` INT NOT NULL,
  PRIMARY KEY (`CPF_zela`, `Apoio_idApoio`),
  INDEX `fk_Zeladoria_Apoio1_idx` (`Apoio_idApoio` ASC) VISIBLE,
  CONSTRAINT `fk_Zeladoria_Apoio1`
    FOREIGN KEY (`Apoio_idApoio`)
    REFERENCES `Hospital_db`.`Apoio` (`idApoio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Compras` (
  `idCompras` INT NOT NULL,
  `Farmacia_idRemedio` INT NOT NULL,
  PRIMARY KEY (`idCompras`, `Farmacia_idRemedio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`fechamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`fechamento` (
  `idfechamento` INT NOT NULL,
  PRIMARY KEY (`idfechamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_farmacia1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_farmacia1` (
  `iditem_farmacia` INT NOT NULL,
  PRIMARY KEY (`iditem_farmacia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Item_farmacia2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Item_farmacia2` (
  `idItem_farmacia2` INT NOT NULL,
  PRIMARY KEY (`idItem_farmacia2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_farmacia3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_farmacia3` (
  `iditem_farmacia3` INT NOT NULL,
  PRIMARY KEY (`iditem_farmacia3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`mapa_compras_farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`mapa_compras_farmacia` (
  `idmapa_compras_farmacia` INT NOT NULL,
  `Farmacia_idRemedio` INT NOT NULL,
  `item_farmacia1_iditem_farmacia` INT NOT NULL,
  `Item_farmacia2_idItem_farmacia2` INT NOT NULL,
  `item_farmacia3_iditem_farmacia3` INT NOT NULL,
  `fechamento_idfechamento` INT NOT NULL,
  PRIMARY KEY (`idmapa_compras_farmacia`, `fechamento_idfechamento`),
  INDEX `fk_mapa_compras_farmacia_Farmacia1_idx` (`Farmacia_idRemedio` ASC) VISIBLE,
  INDEX `fk_mapa_compras_farmacia_item_farmacia11_idx` (`item_farmacia1_iditem_farmacia` ASC) VISIBLE,
  INDEX `fk_mapa_compras_farmacia_Item_farmacia21_idx` (`Item_farmacia2_idItem_farmacia2` ASC) VISIBLE,
  INDEX `fk_mapa_compras_farmacia_item_farmacia31_idx` (`item_farmacia3_iditem_farmacia3` ASC) VISIBLE,
  INDEX `fk_mapa_compras_farmacia_fechamento1_idx` (`fechamento_idfechamento` ASC) VISIBLE,
  CONSTRAINT `fk_mapa_compras_farmacia_Farmacia1`
    FOREIGN KEY (`Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Farmacia` (`idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_farmacia_item_farmacia11`
    FOREIGN KEY (`item_farmacia1_iditem_farmacia`)
    REFERENCES `Hospital_db`.`item_farmacia1` (`iditem_farmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_farmacia_Item_farmacia21`
    FOREIGN KEY (`Item_farmacia2_idItem_farmacia2`)
    REFERENCES `Hospital_db`.`Item_farmacia2` (`idItem_farmacia2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_farmacia_item_farmacia31`
    FOREIGN KEY (`item_farmacia3_iditem_farmacia3`)
    REFERENCES `Hospital_db`.`item_farmacia3` (`iditem_farmacia3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_farmacia_fechamento1`
    FOREIGN KEY (`fechamento_idfechamento`)
    REFERENCES `Hospital_db`.`fechamento` (`idfechamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio1` (
  `iditem_compra_apoio1` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio2` (
  `iditem_compra_apoio2` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio3` (
  `iditem_compra_apoio3` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio4` (
  `iditem_compra_apoio4` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio4`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio5` (
  `iditem_compra_apoio5` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio5`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`item_compra_apoio6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`item_compra_apoio6` (
  `iditem_compra_apoio6` INT NOT NULL,
  PRIMARY KEY (`iditem_compra_apoio6`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`mapa_compras_apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`mapa_compras_apoio` (
  `idmapa_compras_apoio` INT NOT NULL,
  `item_compra_apoio1_iditem_compra_apoio1` INT NOT NULL,
  `item_compra_apoio2_iditem_compra_apoio2` INT NOT NULL,
  `item_compra_apoio3_iditem_compra_apoio3` INT NOT NULL,
  `item_compra_apoio4_iditem_compra_apoio4` INT NOT NULL,
  `item_compra_apoio5_iditem_compra_apoio5` INT NOT NULL,
  `item_compra_apoio6_iditem_compra_apoio6` INT NOT NULL,
  `Apoio_idApoio` INT NOT NULL,
  `Apoio_Sala_pediatria_idSala_pediatria` INT NOT NULL,
  `Apoio_Sala_pediatria_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Apoio_Sala_pediatria_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  `Apoio_Sala_vermelha_idSala_vermelha` INT NOT NULL,
  `Apoio_Sala_vermelha_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Apoio_Sala_vermelha_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  `Apoio_Apartamentos_Salas_Apartamentos` INT NOT NULL,
  `Apoio_Apartamentos_Recepcao_interna_idRecepcao_interna` INT NOT NULL,
  `Apoio_Apartamentos_Recepcao_interna_Clinica_idClinica` INT NOT NULL,
  `fechamento_idfechamento` INT NOT NULL,
  PRIMARY KEY (`idmapa_compras_apoio`, `fechamento_idfechamento`),
  INDEX `fk_mapa_compras_apoio_item_compra_apoio11_idx` (`item_compra_apoio1_iditem_compra_apoio1` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_item_compra_apoio21_idx` (`item_compra_apoio2_iditem_compra_apoio2` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_item_compra_apoio31_idx` (`item_compra_apoio3_iditem_compra_apoio3` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_item_compra_apoio41_idx` (`item_compra_apoio4_iditem_compra_apoio4` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_item_compra_apoio51_idx` (`item_compra_apoio5_iditem_compra_apoio5` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_item_compra_apoio61_idx` (`item_compra_apoio6_iditem_compra_apoio6` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_Apoio1_idx` (`Apoio_idApoio` ASC, `Apoio_Sala_pediatria_idSala_pediatria` ASC, `Apoio_Sala_pediatria_Recepcao_interna_idRecepcao_interna` ASC, `Apoio_Sala_pediatria_Recepcao_interna_Clinica_idClinica` ASC, `Apoio_Sala_vermelha_idSala_vermelha` ASC, `Apoio_Sala_vermelha_Recepcao_interna_idRecepcao_interna` ASC, `Apoio_Sala_vermelha_Recepcao_interna_Clinica_idClinica` ASC, `Apoio_Apartamentos_Salas_Apartamentos` ASC, `Apoio_Apartamentos_Recepcao_interna_idRecepcao_interna` ASC, `Apoio_Apartamentos_Recepcao_interna_Clinica_idClinica` ASC) VISIBLE,
  INDEX `fk_mapa_compras_apoio_fechamento1_idx` (`fechamento_idfechamento` ASC) VISIBLE,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio11`
    FOREIGN KEY (`item_compra_apoio1_iditem_compra_apoio1`)
    REFERENCES `Hospital_db`.`item_compra_apoio1` (`iditem_compra_apoio1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio21`
    FOREIGN KEY (`item_compra_apoio2_iditem_compra_apoio2`)
    REFERENCES `Hospital_db`.`item_compra_apoio2` (`iditem_compra_apoio2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio31`
    FOREIGN KEY (`item_compra_apoio3_iditem_compra_apoio3`)
    REFERENCES `Hospital_db`.`item_compra_apoio3` (`iditem_compra_apoio3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio41`
    FOREIGN KEY (`item_compra_apoio4_iditem_compra_apoio4`)
    REFERENCES `Hospital_db`.`item_compra_apoio4` (`iditem_compra_apoio4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio51`
    FOREIGN KEY (`item_compra_apoio5_iditem_compra_apoio5`)
    REFERENCES `Hospital_db`.`item_compra_apoio5` (`iditem_compra_apoio5`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_item_compra_apoio61`
    FOREIGN KEY (`item_compra_apoio6_iditem_compra_apoio6`)
    REFERENCES `Hospital_db`.`item_compra_apoio6` (`iditem_compra_apoio6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_Apoio1`
    FOREIGN KEY (`Apoio_idApoio` , `Apoio_Sala_pediatria_idSala_pediatria` , `Apoio_Sala_pediatria_Recepcao_interna_idRecepcao_interna` , `Apoio_Sala_pediatria_Recepcao_interna_Clinica_idClinica` , `Apoio_Sala_vermelha_idSala_vermelha` , `Apoio_Sala_vermelha_Recepcao_interna_idRecepcao_interna` , `Apoio_Sala_vermelha_Recepcao_interna_Clinica_idClinica` , `Apoio_Apartamentos_Salas_Apartamentos` , `Apoio_Apartamentos_Recepcao_interna_idRecepcao_interna` , `Apoio_Apartamentos_Recepcao_interna_Clinica_idClinica`)
    REFERENCES `Hospital_db`.`Apoio` (`idApoio` , `Sala_pediatria_idSala_pediatria` , `Sala_pediatria_Recepcao_interna_idRecepcao_interna` , `Sala_pediatria_Recepcao_interna_Clinica_idClinica` , `Sala_vermelha_idSala_vermelha` , `Sala_vermelha_Recepcao_interna_idRecepcao_interna` , `Sala_vermelha_Recepcao_interna_Clinica_idClinica` , `Apartamentos_Salas_Apartamentos` , `Apartamentos_Recepcao_interna_idRecepcao_interna` , `Apartamentos_Recepcao_interna_Clinica_idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapa_compras_apoio_fechamento1`
    FOREIGN KEY (`fechamento_idfechamento`)
    REFERENCES `Hospital_db`.`fechamento` (`idfechamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`pedidos` (
  `idpedidos` INT NOT NULL,
  `fornecedor` VARCHAR(45) NULL,
  `fechamento_idfechamento` INT NOT NULL,
  `Compras_idCompras` INT NOT NULL,
  `Compras_Farmacia_idRemedio` INT NOT NULL,
  PRIMARY KEY (`idpedidos`, `Compras_idCompras`, `Compras_Farmacia_idRemedio`),
  INDEX `fk_pedidos_fechamento1_idx` (`fechamento_idfechamento` ASC) VISIBLE,
  INDEX `fk_pedidos_Compras1_idx` (`Compras_idCompras` ASC, `Compras_Farmacia_idRemedio` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_fechamento1`
    FOREIGN KEY (`fechamento_idfechamento`)
    REFERENCES `Hospital_db`.`fechamento` (`idfechamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_Compras1`
    FOREIGN KEY (`Compras_idCompras` , `Compras_Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Compras` (`idCompras` , `Farmacia_idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`financeiro` (
  `idfinanceiro` INT NOT NULL,
  PRIMARY KEY (`idfinanceiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Diretora_ADM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Diretora_ADM` (
  `CPF_dir_adm` INT NOT NULL,
  `Nome_dir_adm` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Telefone_dri_adm` INT(11) NULL,
  `Compras_idCompras` INT NOT NULL,
  `Compras_Farmacia_idRemedio` INT NOT NULL,
  `financeiro_idfinanceiro` INT NOT NULL,
  PRIMARY KEY (`CPF_dir_adm`, `Compras_idCompras`, `Compras_Farmacia_idRemedio`, `financeiro_idfinanceiro`),
  INDEX `fk_Diretora_ADM_Compras1_idx` (`Compras_idCompras` ASC, `Compras_Farmacia_idRemedio` ASC) VISIBLE,
  INDEX `fk_Diretora_ADM_financeiro1_idx` (`financeiro_idfinanceiro` ASC) VISIBLE,
  CONSTRAINT `fk_Diretora_ADM_Compras1`
    FOREIGN KEY (`Compras_idCompras` , `Compras_Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Compras` (`idCompras` , `Farmacia_idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diretora_ADM_financeiro1`
    FOREIGN KEY (`financeiro_idfinanceiro`)
    REFERENCES `Hospital_db`.`financeiro` (`idfinanceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`faturamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`faturamento` (
  `idfaturamento` INT NOT NULL,
  `valor_faturamento` DECIMAL NULL,
  `data_faturamento` DATE NULL,
  `historico_de_pagamentos_idhistorico_de_pagamentos` INT NOT NULL,
  `Diretora_ADM_CPF_dir_adm` INT NOT NULL,
  `Diretora_ADM_Compras_idCompras` INT NOT NULL,
  `Diretora_ADM_Compras_Farmacia_idRemedio` INT NOT NULL,
  `Diretora_ADM_financeiro_idfinanceiro` INT NOT NULL,
  PRIMARY KEY (`idfaturamento`, `historico_de_pagamentos_idhistorico_de_pagamentos`, `Diretora_ADM_CPF_dir_adm`, `Diretora_ADM_Compras_idCompras`, `Diretora_ADM_Compras_Farmacia_idRemedio`, `Diretora_ADM_financeiro_idfinanceiro`),
  INDEX `fk_faturamento_Diretora_ADM1_idx` (`Diretora_ADM_CPF_dir_adm` ASC, `Diretora_ADM_Compras_idCompras` ASC, `Diretora_ADM_Compras_Farmacia_idRemedio` ASC, `Diretora_ADM_financeiro_idfinanceiro` ASC) VISIBLE,
  CONSTRAINT `fk_faturamento_Diretora_ADM1`
    FOREIGN KEY (`Diretora_ADM_CPF_dir_adm` , `Diretora_ADM_Compras_idCompras` , `Diretora_ADM_Compras_Farmacia_idRemedio` , `Diretora_ADM_financeiro_idfinanceiro`)
    REFERENCES `Hospital_db`.`Diretora_ADM` (`CPF_dir_adm` , `Compras_idCompras` , `Compras_Farmacia_idRemedio` , `financeiro_idfinanceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Pagamentos` (
  `idpagamentos` INT NOT NULL,
  `financeiro_idfinanceiro` INT NOT NULL,
  `pedidos_idpedidos` INT NOT NULL,
  `pedidos_Compras_idCompras` INT NOT NULL,
  `pedidos_Compras_Farmacia_idRemedio` INT NOT NULL,
  PRIMARY KEY (`idpagamentos`, `financeiro_idfinanceiro`, `pedidos_idpedidos`, `pedidos_Compras_idCompras`, `pedidos_Compras_Farmacia_idRemedio`),
  INDEX `fk_Pagamentos_financeiro1_idx` (`financeiro_idfinanceiro` ASC) VISIBLE,
  INDEX `fk_Pagamentos_pedidos1_idx` (`pedidos_idpedidos` ASC, `pedidos_Compras_idCompras` ASC, `pedidos_Compras_Farmacia_idRemedio` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_financeiro1`
    FOREIGN KEY (`financeiro_idfinanceiro`)
    REFERENCES `Hospital_db`.`financeiro` (`idfinanceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamentos_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos` , `pedidos_Compras_idCompras` , `pedidos_Compras_Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`pedidos` (`idpedidos` , `Compras_idCompras` , `Compras_Farmacia_idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Historico_de_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Historico_de_pagamentos` (
  `faturamento_idfaturamento` INT NOT NULL,
  `faturamento_historico_de_pagamentos_idhistorico_de_pagamentos` INT NOT NULL,
  `Pagamentos_idpagamentos` INT NOT NULL,
  `Pagamentos_financeiro_idfinanceiro` INT NOT NULL,
  `Pagamentos_pedidos_idpedidos` INT NOT NULL,
  `Pagamentos_pedidos_Compras_idCompras` INT NOT NULL,
  `Pagamentos_pedidos_Compras_Farmacia_idRemedio` INT NOT NULL,
  PRIMARY KEY (`faturamento_idfaturamento`, `faturamento_historico_de_pagamentos_idhistorico_de_pagamentos`, `Pagamentos_idpagamentos`, `Pagamentos_financeiro_idfinanceiro`, `Pagamentos_pedidos_idpedidos`, `Pagamentos_pedidos_Compras_idCompras`, `Pagamentos_pedidos_Compras_Farmacia_idRemedio`),
  INDEX `fk_faturamento_has_Pagamentos_Pagamentos1_idx` (`Pagamentos_idpagamentos` ASC, `Pagamentos_financeiro_idfinanceiro` ASC, `Pagamentos_pedidos_idpedidos` ASC, `Pagamentos_pedidos_Compras_idCompras` ASC, `Pagamentos_pedidos_Compras_Farmacia_idRemedio` ASC) VISIBLE,
  INDEX `fk_faturamento_has_Pagamentos_faturamento1_idx` (`faturamento_idfaturamento` ASC, `faturamento_historico_de_pagamentos_idhistorico_de_pagamentos` ASC) VISIBLE,
  CONSTRAINT `fk_faturamento_has_Pagamentos_faturamento1`
    FOREIGN KEY (`faturamento_idfaturamento` , `faturamento_historico_de_pagamentos_idhistorico_de_pagamentos`)
    REFERENCES `Hospital_db`.`faturamento` (`idfaturamento` , `historico_de_pagamentos_idhistorico_de_pagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faturamento_has_Pagamentos_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idpagamentos` , `Pagamentos_financeiro_idfinanceiro` , `Pagamentos_pedidos_idpedidos` , `Pagamentos_pedidos_Compras_idCompras` , `Pagamentos_pedidos_Compras_Farmacia_idRemedio`)
    REFERENCES `Hospital_db`.`Pagamentos` (`idpagamentos` , `financeiro_idfinanceiro` , `pedidos_idpedidos` , `pedidos_Compras_idCompras` , `pedidos_Compras_Farmacia_idRemedio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Consultorio` (
  `idconsultorio` INT NOT NULL,
  `Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  PRIMARY KEY (`idconsultorio`, `Registro_Pacientes_CPF`, `Registro_recepcao_externa_guiche_recepcao`),
  INDEX `fk_Consultorio_Registro1_idx` (`Registro_Pacientes_CPF` ASC, `Registro_recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  CONSTRAINT `fk_Consultorio_Registro1`
    FOREIGN KEY (`Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`Registro` (`Pacientes_CPF` , `recepcao_externa_guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Pediatria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Pediatria` (
  `CRM_pedi` INT NOT NULL,
  `Nome_pedi` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `Sus_pedi` INT(15) NULL,
  `Turno_pedi` BINARY(2) NULL,
  `Telefone_pedi` INT(11) NULL,
  `Consultorio_idconsultorio` INT NOT NULL,
  `Consultorio_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Consultorio_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_pedi`, `Consultorio_idconsultorio`, `Consultorio_Registro_Pacientes_CPF`, `Consultorio_Registro_recepcao_externa_guiche_recepcao`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Pediatria_Consultorio1_idx` (`Consultorio_idconsultorio` ASC, `Consultorio_Registro_Pacientes_CPF` ASC, `Consultorio_Registro_recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  INDEX `fk_Pediatria_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Pediatria_Consultorio1`
    FOREIGN KEY (`Consultorio_idconsultorio` , `Consultorio_Registro_Pacientes_CPF` , `Consultorio_Registro_recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`Consultorio` (`idconsultorio` , `Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pediatria_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Ortopedista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Ortopedista` (
  `CRM_orto` INT NOT NULL,
  `Nome_orto` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `SUS_orto` INT(15) NULL,
  `Turno_orto` BINARY(2) NULL,
  `telefone_orto` INT(11) NULL,
  `Consultorio_idconsultorio` INT NOT NULL,
  `Consultorio_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Consultorio_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_orto`, `Consultorio_idconsultorio`, `Consultorio_Registro_Pacientes_CPF`, `Consultorio_Registro_recepcao_externa_guiche_recepcao`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Ortopedista_Consultorio1_idx` (`Consultorio_idconsultorio` ASC, `Consultorio_Registro_Pacientes_CPF` ASC, `Consultorio_Registro_recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  INDEX `fk_Ortopedista_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Ortopedista_Consultorio1`
    FOREIGN KEY (`Consultorio_idconsultorio` , `Consultorio_Registro_Pacientes_CPF` , `Consultorio_Registro_recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`Consultorio` (`idconsultorio` , `Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ortopedista_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital_db`.`Ginecologista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital_db`.`Ginecologista` (
  `CRM_go` INT NOT NULL,
  `Nome_go` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `SUS_go` INT(15) NULL,
  `turno_go` BINARY(2) NULL,
  `Telefone` INT(11) NULL,
  `Consultorio_idconsultorio` INT NOT NULL,
  `Consultorio_Registro_Pacientes_CPF` INT(11) NOT NULL,
  `Consultorio_Registro_recepcao_externa_guiche_recepcao` INT NOT NULL,
  `Diretor_tecnico_CRM_dire` INT NOT NULL,
  PRIMARY KEY (`CRM_go`, `Consultorio_idconsultorio`, `Consultorio_Registro_Pacientes_CPF`, `Consultorio_Registro_recepcao_externa_guiche_recepcao`, `Diretor_tecnico_CRM_dire`),
  INDEX `fk_Ginecologista_Consultorio1_idx` (`Consultorio_idconsultorio` ASC, `Consultorio_Registro_Pacientes_CPF` ASC, `Consultorio_Registro_recepcao_externa_guiche_recepcao` ASC) VISIBLE,
  INDEX `fk_Ginecologista_Diretor_tecnico1_idx` (`Diretor_tecnico_CRM_dire` ASC) VISIBLE,
  CONSTRAINT `fk_Ginecologista_Consultorio1`
    FOREIGN KEY (`Consultorio_idconsultorio` , `Consultorio_Registro_Pacientes_CPF` , `Consultorio_Registro_recepcao_externa_guiche_recepcao`)
    REFERENCES `Hospital_db`.`Consultorio` (`idconsultorio` , `Registro_Pacientes_CPF` , `Registro_recepcao_externa_guiche_recepcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ginecologista_Diretor_tecnico1`
    FOREIGN KEY (`Diretor_tecnico_CRM_dire`)
    REFERENCES `Hospital_db`.`Diretor_tecnico` (`CRM_dire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
